# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conn.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 340)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.saved = QtWidgets.QComboBox(Dialog)
        self.saved.setObjectName("saved")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.saved)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setObjectName("name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.host = QtWidgets.QLineEdit(Dialog)
        self.host.setObjectName("host")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.host)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.port = QtWidgets.QLineEdit(Dialog)
        self.port.setObjectName("port")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.port)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.username = QtWidgets.QLineEdit(Dialog)
        self.username.setObjectName("username")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.username)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setObjectName("password")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.password)
        self.verticalLayout.addLayout(self.formLayout)
        self.remember = QtWidgets.QCheckBox(Dialog)
        self.remember.setChecked(True)
        self.remember.setObjectName("remember")
        self.verticalLayout.addWidget(self.remember)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "已保存的连接"))
        self.label_6.setText(_translate("Dialog", "名称"))
        self.name.setPlaceholderText(_translate("Dialog", "可选，默认 主机:端口"))
        self.label.setText(_translate("Dialog", "host*"))
        self.label_2.setText(_translate("Dialog", "port*"))
        self.label_3.setText(_translate("Dialog", "username"))
        self.label_4.setText(_translate("Dialog", "password*"))
        self.remember.setText(_translate("Dialog", "记住此连接"))
